"""
Visualize the LangGraph pipeline and save to files.

Run from langchain_agent (use project venv if you have one):
  python visualize_pipeline.py
  # or: Amp-venv\\Scripts\\python.exe visualize_pipeline.py

Outputs:
  - pipeline_graph.mmd   Mermaid source
  - pipeline_graph.md   Markdown with Mermaid (renders on GitHub)
  - pipeline_graph.png   PNG image (if draw_mermaid_png works)
  - pipeline_graph_ascii.txt  ASCII art (if grandalf is installed)
"""
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))

from agent.pipeline_graph import build_pipeline_graph


def main():
    out_dir = Path(__file__).resolve().parent
    app = build_pipeline_graph()
    g = app.get_graph()

    # 1. Mermaid source (render in GitHub, Mermaid Live, or docs)
    mermaid = g.draw_mermaid()
    mermaid_path = out_dir / "pipeline_graph.mmd"
    mermaid_path.write_text(mermaid, encoding="utf-8")
    print("Wrote Mermaid:", mermaid_path)

    # 2. ASCII (terminal-friendly)
    try:
        ascii_art = g.draw_ascii()
        ascii_path = out_dir / "pipeline_graph_ascii.txt"
        ascii_path.write_text(ascii_art, encoding="utf-8")
        print("Wrote ASCII:", ascii_path)
        print("\n--- ASCII preview ---\n")
        print(ascii_art)
    except Exception as e:
        print("ASCII draw skipped:", e)

    # 3. PNG (optional; may require playwright/puppeteer)
    png_path = out_dir / "pipeline_graph.png"
    try:
        png_bytes = g.draw_mermaid_png()
        if png_bytes:
            png_path.write_bytes(png_bytes)
            print("Wrote PNG:", png_path)
        else:
            print("PNG not available (install playwright or use Mermaid CLI).")
    except Exception as e:
        print("PNG draw skipped:", e)

    # 4. Markdown with embedded Mermaid (for GitHub/docs)
    md_path = out_dir / "pipeline_graph.md"
    md_content = """# Pipeline graph (LangGraph)

Generated by `python visualize_pipeline.py`. Renders in GitHub and any Mermaid viewer.

```mermaid
"""
    md_content += mermaid.strip()
    md_content += "\n```\n"
    md_path.write_text(md_content, encoding="utf-8")
    print("Wrote Markdown:", md_path)


if __name__ == "__main__":
    main()
